//
// Created by M Lunkeit on 28.07.26.
//

#ifndef BASALT_BIP39_H
#define BASALT_BIP39_H

#include <stddef.h>
#include <stdint.h>

#include "error.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BASALT_BIP39_MAX_WORD_LENGTH 9
#define BASALT_BIP39_WORDS 12

/**
 * @brief Holds a single null-terminated BIP-39 word.
 *
 * This structure contains a single BIP-39 word.
 *
 * Please note that the word hold by the char array is null-terminated.
 * Therefore a length of at least 9 characters is required as the longest
 * BIP-39 word has a total of 8 characters.
 */
typedef struct {
    char word[BASALT_BIP39_MAX_WORD_LENGTH];
} basalt_keyder_word_t;

/**
 * @brief Holds a SECRET BIP-39 mnemonic.
 *
 * This structure contains a whole BIP-39 mnemonic.
 *
 * A BIP-39 mnemonic consists of 12 words. All of these are stored inside
 * this structure.
 *
 * @warning     The contents of this structure have to be kept secret
 *              under all circumstances. It will be possible to derive
 *              private keys from this 12 word array. Therefore you
 *              would want to protect the contents of this structure
 *              from all unauthorized access.
 */
typedef struct {
    basalt_keyder_word_t words[BASALT_BIP39_WORDS];
} basalt_keyder_mnemonic_t;

/**
 * @brief Generates 12 words from a given entropy.
 *
 * This function generates 12 words for usage with BIP-39.
 *
 * It uses the SHA-256 hash algorithm to convert the 128-bit entropy
 * into an 132-bit seed. This seed is generated by taking the entire
 * 128-bit entropy and then appending the 4 most significant bits
 * from the SHA-256 hash value.
 *
 * This seed is then divided into 12 11-bit sections. Each 11-bit
 * section holds a number from 0 to 2047. Each 11-bit number is
 * then mapped to a word in a list of 2048 words.
 *
 * @warning     When calling this function, PLEASE MAKE SURE, that the 128-bit
 *              entropy is NOT generated by any deterministic number generation
 *              function. Please use UNPREDICTABLE NOISE, otherwise the generated
 *              mnemonic is NOT safe.
 *
 * @param[out]  mnemonic    a pointer to where the mnemonic will be stored
 * @param[in]   entropy     16 random bytes (128 bits of entropy)
 *
 * @return      the error code, 0 otherwise
 */
basalt_err_t basalt_keyder_generate_mnemonic(basalt_keyder_mnemonic_t *mnemonic, const uint8_t entropy[16]);

#ifdef __cplusplus
}
#endif

#endif //BASALT_BIP39_H
