//
// Created by M Lunkeit on 28.07.26.
//

#ifndef BASALT_BIP39_H
#define BASALT_BIP39_H

#include <stddef.h>
#include <stdint.h>

#include "basalt/error.h"
#include "basalt/ec.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BASALT_BIP32_KEY_BYTES      32
#define BASALT_BIP39_ENTROPY_BYTES  16
#define BASALT_BIP39_SEED_BYTES     64

typedef struct {
    basalt_ec_private_key_t key;
    uint8_t c[BASALT_BIP32_KEY_BYTES];
} basalt_keyder_extended_private_key_t;

typedef struct {
    basalt_ec_compressed_public_key_t key;
    uint8_t c[BASALT_BIP32_KEY_BYTES];
} basalt_keyder_extended_public_key_t;

/**
 * @brief Generates 12 words from a given entropy.
 *
 * This function generates 12 words for usage with BIP-39. It writes a null
 * terminated mnemonic string into the given output char array. So please
 * make sure that there is enough space to write to.
 *
 * It uses the SHA-256 hash algorithm to convert the 128-bit entropy
 * into an 132-bit entropy with checksum. This "extended" entropy is
 * generated by taking the entire 128-bit entropy and then appending
 * the 4 most significant bits from the SHA-256 hash value.
 *
 * This seed is then divided into 12 11-bit sections. Each 11-bit
 * section holds a number from 0 to 2047. Each 11-bit number is
 * then mapped to a word in a list of 2048 words.
 *
 * @warning     When calling this function, PLEASE MAKE SURE, that the 128-bit
 *              entropy is NOT generated by any deterministic number generation
 *              function. Please use UNPREDICTABLE NOISE, otherwise the generated
 *              mnemonic is NOT safe.
 *
 * @param[out]  mnemonic    a pointer to where the mnemonic will be stored
 * @param[in]   entropy     16 random bytes (128 bits of entropy)
 *
 * @return      the error code, 0 otherwise
 */
basalt_err_t basalt_keyder_generate_mnemonic(char *mnemonic, const uint8_t entropy[BASALT_BIP39_ENTROPY_BYTES]);

basalt_err_t basalt_keyder_derive_seed(uint8_t seed[BASALT_BIP39_SEED_BYTES], const char *mnemonic, const char *passphrase);

basalt_err_t basalt_keyder_derive_root(basalt_keyder_extended_private_key_t *root, const uint8_t seed[BASALT_BIP39_SEED_BYTES]);

/**
 * @brief Derives a private extended child key from a private extended parent key.
 *
 * This function uses the BIP-32 standard for key derivation with a given path.
 *
 * Please note that the BIP-32 standard only works with 256 bit curves. It takes in
 * a 512 bit parent "extended" key and outputs a 512 bit child "extended" key.
 * The chain code ("extension") is necessary to derive further public and private keys.
 *
 * @param[out]  child       a pointer to the derived extended child key
 * @param[in]   parent      a pointer to the extended parent key
 * @param[in]   path        the derivation path
 * @param[in]   len_path    the length of the derivation path (may be 0)
 *
 * @return      the error code, 0 otherwise
 */
basalt_err_t basalt_keyder_derive_private(
    basalt_keyder_extended_private_key_t *child,
    const basalt_keyder_extended_private_key_t *parent,
    const uint32_t *path, size_t len_path
);

/**
 * @brief Derives a public extended child key from a public extended parent key.
 *
 * This function uses the BIP-32 standard for key derivation with a given path.
 *
 * Please note that the BIP-32 standard only works with 256 bit curves. It takes
 * in a 520 bit parent "extended" key and outputs a 520 bit child "extended" key.
 * The chain code ("extension") is necessary to derive further public keys.
 *
 * Furthermore, it is NOT possible to derive hardened keys. This means that every
 * path element must be smaller than 2^31.
 *
 * @param[out]  child       a pointer to the derived extended child key
 * @param[in]   parent      a pointer to the extended parent key
 * @param[in]   path        the derivation path
 * @param[in]   len_path    the length of the derivation path (may be 0)
 *
 * @return      the error code, 0 otherwise
 */
basalt_err_t basalt_keyder_derive_public(
    basalt_keyder_extended_public_key_t *child,
    const basalt_keyder_extended_public_key_t *parent,
    const uint32_t *path, size_t len_path
);

#ifdef __cplusplus
}
#endif

#endif //BASALT_BIP39_H
